### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Intiiii** [BedWarMod/BedWar#5]
Hii, im getting some kind of error with the api...

```
BedWar Mod 0.1.7.Pre.1: Api JSON syntax error
 
Caused by kotlin.collections.builders.ListBuilder: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 8 path $
	at com.google.gson.JsonParser.parse(JsonParser.java:65)
	at com.google.gson.JsonParser.parse(JsonParser.java:45)
	at BW.utils.ApiUtils.getJSONResponse(ApiUtils.kt:69)
	at BW.utils.ApiUtils.access$getJSONResponse(ApiUtils.kt:20)
	at BW.utils.ApiUtils$getBedwarsStats$result$1.invokeSuspend(ApiUtils.kt:120)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
Caused by kotlin.collections.builders.ListBuilder: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 8 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
	at com.google.gson.JsonParser.parse(JsonParser.java:60)
```

![image](https://github.com/user-attachments/assets/e3f16d09-8c08-4b53-963a-fa3374be6377)
if I run just /bws,

![image](https://github.com/user-attachments/assets/6a9aec45-751c-4750-993a-ca0de97c84ee)
if I run /bws with a playername

**Comment by unparted** [comment]
Do you have an API key? Did you input it into the mod?
